<a href="https://colab.research.google.com/github/kimheeseo/2022_Efficient-ML/blob/main/in-place_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
출처 : https://intrepidgeeks.com/tutorial/let-me-explain-the-meaning-of-inplace-operation-in-pytorch

In [5]:
import torch
x=torch.rand(2)
print(x)

tensor([0.9965, 0.9818])


In [6]:
y=torch.rand(2)
y

tensor([0.1917, 0.2594])

In [7]:
x.add_(y)
print(x) 

tensor([1.1882, 1.2412])


In [ ]:
#0.9965+0.1917=1.1882
#0.9818+0.2594=1.2412

#x값 (0.9965 0.9818) -> (1.1882,1.2412)

#제자리 조작 부호 = in-place operation은 pytorch 에서 tensor의 값을 바꿀때
#복사 작업을 거치지 않고 원래 메모리에서 값을 직접 바꾸는것을 말한다. 

In [9]:
x+y

tensor([1.3800, 1.5005])